from django.urls import path

from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("owner/", views.owner_console, name="owner_console"),
    path("owner/setup/", views.owner_setup, name="owner_setup"),
    path("start/", views.start, name="start"),
    path("study/", views.study_home, name="study_home"),
    path("study/digests/", views.digest_overview, name="digest_overview"),
    path("study/digests/<int:pk>/", views.digest_detail, name="digest_detail"),
    path("study/timeline/", views.timeline_view, name="timeline"),
    path("study/reviews/", views.review_queue, name="review_queue"),
    path("study/reviews/<int:pk>/done/", views.review_mark_done, name="review_mark_done"),
    path("study/reviews/<int:pk>/skip/", views.review_skip, name="review_skip"),
    path("study/resources/", views.resource_radar, name="resource_radar"),
    path("study/route/", views.learning_route, name="learning_route"),
    path("study/routes/", views.learning_routes, name="learning_routes"),
    path("integrations/muele/", views.muele_connection, name="muele_connection"),
    path("integrations/muele/connect/", views.muele_connect, name="muele_connect"),
    path("integrations/muele/courses/", views.muele_courses, name="muele_courses"),
    path("api/muele/status/", views.muele_sync_status, name="muele_sync_status"),
    path("profiles/", views.profiles_list, name="profiles_list"),
    path("profiles/new/", views.profile_wizard, name="profile_wizard"),
    path("profiles/new/makerere/", views.makerere_wizard, name="makerere_wizard"),
    path("profiles/<int:pk>/edit/", views.profile_edit, name="profile_edit"),
    path("profiles/<int:pk>/activate/", views.profile_activate, name="profile_activate"),
    path("profiles/<int:pk>/delete/", views.profile_delete, name="profile_delete"),
    path("settings/", views.settings_edit, name="settings_edit"),
    path("api/browse-folders/", views.browse_folders, name="browse_folders"),
    path("moves/<int:pk>/summarize/", views.move_summarize, name="move_summarize"),
    path("moves/<int:pk>/summary/", views.move_summary_view, name="move_summary_view"),
    path("moves/<int:pk>/summary.pdf", views.move_summary_pdf, name="move_summary_pdf"),
    path("profiles/<int:profile_pk>/courses/<str:code>/guide/generate/", views.course_guide_generate, name="course_guide_generate"),
    path("study/subjects/", views.subject_dashboard, name="subject_dashboard"),
    path("study/exports/", views.export_bundles, name="export_bundles"),
    path("study/exports/<int:pk>/download/", views.export_download, name="export_download"),
    path("study/exports/<int:pk>/delete/", views.export_delete, name="export_delete"),
    path("study/setup/", views.first_run_checklist, name="first_run"),
    path("study/undo/", views.undo_recent, name="undo_recent"),
    path("api/rule-test/", views.rule_test, name="rule_test"),
    path("api/preview-scan/", views.preview_scan, name="preview_scan"),
    path("study/inbox/", views.sorting_inbox, name="sorting_inbox"),
    path("study/inbox/<int:pk>/approve/", views.inbox_approve, name="inbox_approve"),
    path("study/inbox/<int:pk>/reroute/", views.inbox_reroute, name="inbox_reroute"),
    path("study/inbox/<int:pk>/ignore/", views.inbox_ignore, name="inbox_ignore"),
    path("study/rules/", views.folder_rules, name="folder_rules"),
    path("study/import/", views.import_plans, name="import_plans"),
    path("study/subjects/<str:code>/", views.subject_memory_detail, name="subject_memory_detail"),
    path("profiles/<int:profile_pk>/courses/<str:code>/guide/", views.course_guide_view, name="course_guide_view"),
    path("profiles/<int:profile_pk>/courses/<str:code>/guide.pdf", views.course_guide_pdf, name="course_guide_pdf"),
]
