# Generated by Django 6.0.6 on 2026-07-19 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloads_path', models.CharField(max_length=1024)),
                ('secondary_downloads_path', models.CharField(blank=True, help_text='Optional second folder to watch, e.g. downloads on another drive. Leave blank to disable.', max_length=1024)),
                ('library_inbox_path', models.CharField(max_length=1024)),
                ('installer_stale_days', models.PositiveIntegerField(default=30)),
                ('installer_delete_days', models.PositiveIntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('purpose', models.CharField(choices=[('school', 'School'), ('online', 'Online learning'), ('research', 'Research'), ('work', 'Work training'), ('custom', 'Custom')], default='custom', max_length=16)),
                ('primary_label', models.CharField(default='Year', max_length=32)),
                ('secondary_label', models.CharField(default='Semester', max_length=32)),
                ('root_path', models.CharField(help_text='Folder this profile organizes files into', max_length=1024)),
                ('ai_fallback_enabled', models.BooleanField(default=False, help_text='Optional: use an AI classifier as a last resort for files that match nothing else. Needs your own API key in ai_config.json.')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MoveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=512)),
                ('source_path', models.CharField(max_length=1024)),
                ('destination_path', models.CharField(blank=True, max_length=1024)),
                ('method', models.CharField(choices=[('course_code', 'Subject code in filename'), ('topic', 'Topic keyword match'), ('ai', 'AI classification'), ('ebook', 'Ebook detected'), ('sensitive', 'Sensitive filename/extension'), ('media', 'Media file type'), ('installer', 'Installer'), ('archive', 'Archive file'), ('work_unsorted', 'Code/project file'), ('unsorted', 'No match -- _Unsorted'), ('needs_sorting', 'No match -- _NeedsSorting')], max_length=32)),
                ('course_code', models.CharField(blank=True, max_length=16, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.CharField(blank=True, max_length=1024)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_events', to='organizer.profile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CourseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_value', models.CharField(max_length=64)),
                ('secondary_value', models.CharField(max_length=64)),
                ('groups', models.JSONField(default=list, help_text='Course/subject/module codes for this profile')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='organizer.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('primary_value', models.CharField(max_length=64)),
                ('secondary_value', models.CharField(max_length=64)),
                ('archived', models.BooleanField(default=False)),
                ('keywords', models.JSONField(default=list)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_entries', to='organizer.profile')),
            ],
            options={
                'unique_together': {('profile', 'code')},
            },
        ),
    ]
