# Generated by Django 6.0.6 on 2026-07-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_year', models.CharField(max_length=32)),
                ('current_semester', models.CharField(max_length=32)),
                ('courses', models.JSONField(default=list, help_text='Course codes for the current semester')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('year', models.CharField(max_length=32)),
                ('semester', models.CharField(max_length=32)),
                ('archived', models.BooleanField(default=False)),
                ('keywords', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='MoveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=512)),
                ('source_path', models.CharField(max_length=1024)),
                ('destination_path', models.CharField(blank=True, max_length=1024)),
                ('method', models.CharField(choices=[('course_code', 'Course code in filename'), ('topic', 'Topic keyword match'), ('ai', 'AI classification'), ('ebook', 'Ebook detected'), ('sensitive', 'Sensitive filename/extension'), ('media', 'Media file type'), ('installer', 'Installer'), ('archive', 'Archive file'), ('work_unsorted', 'Code/project file'), ('unsorted', 'No match -- _Unsorted'), ('needs_sorting', 'No match -- _NeedsSorting')], max_length=32)),
                ('course_code', models.CharField(blank=True, max_length=16, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.CharField(blank=True, max_length=1024)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
