# Generated by Django 6.0.6 on 2026-07-19 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('profile', 'Profile'), ('subject', 'Subject'), ('term', 'Term')], default='profile', max_length=16)),
                ('subject_code', models.CharField(blank=True, max_length=32)),
                ('title', models.CharField(max_length=180)),
                ('output_path', models.CharField(blank=True, max_length=1024)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('building', 'Building'), ('ready', 'Ready'), ('failed', 'Failed')], default='draft', max_length=16)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_bundles', to='organizer.profile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('muele', 'Makerere MUELE'), ('moodle', 'Moodle'), ('calendar', 'Calendar'), ('drive', 'Cloud drive'), ('notion', 'Notion'), ('local', 'Local folder')], max_length=24)),
                ('display_name', models.CharField(max_length=120)),
                ('base_url', models.URLField(blank=True)),
                ('username', models.CharField(blank=True, max_length=160)),
                ('token_reference', models.CharField(blank=True, max_length=240)),
                ('status', models.CharField(choices=[('planned', 'Ready to connect'), ('connected', 'Connected'), ('paused', 'Paused'), ('error', 'Needs attention')], default='planned', max_length=24)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_connections', to='organizer.profile')),
            ],
            options={
                'ordering': ['provider', 'display_name'],
                'unique_together': {('profile', 'provider', 'display_name')},
            },
        ),
        migrations.CreateModel(
            name='LearningActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('file_sorted', 'File sorted'), ('summary_created', 'Summary created'), ('review_scheduled', 'Review scheduled'), ('digest_created', 'Digest created'), ('muele_sync', 'MUELE sync'), ('manual_note', 'Manual note')], max_length=32)),
                ('subject_code', models.CharField(blank=True, max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('details', models.TextField(blank=True)),
                ('happened_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('move_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_activities', to='organizer.moveevent')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_activities', to='organizer.profile')),
            ],
            options={
                'ordering': ['-happened_at'],
                'indexes': [models.Index(fields=['profile', '-happened_at'], name='organizer_l_profile_d0fd37_idx'), models.Index(fields=['profile', 'subject_code'], name='organizer_l_profile_87e0e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='LearningDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('title', models.CharField(max_length=180)),
                ('content', models.TextField(blank=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_digests', to='organizer.profile')),
            ],
            options={
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['profile', '-period_end'], name='organizer_l_profile_96131f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(blank=True, max_length=32)),
                ('title', models.CharField(max_length=180)),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('done', 'Done'), ('skipped', 'Skipped')], default='queued', max_length=16)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('move_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_items', to='organizer.moveevent')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to='organizer.profile')),
            ],
            options={
                'ordering': ['status', 'due_at', '-created_at'],
                'indexes': [models.Index(fields=['profile', 'status', 'due_at'], name='organizer_r_profile_0d83cd_idx'), models.Index(fields=['profile', 'subject_code'], name='organizer_r_profile_135e97_idx')],
            },
        ),
        migrations.CreateModel(
            name='SortingInboxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=512)),
                ('source_path', models.CharField(blank=True, max_length=1024)),
                ('suggested_subject', models.CharField(blank=True, max_length=32)),
                ('suggested_destination', models.CharField(blank=True, max_length=1024)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rerouted', 'Rerouted'), ('ignored', 'Ignored')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('move_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorting_inbox_item', to='organizer.moveevent')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorting_inbox_items', to='organizer.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile', 'status'], name='organizer_s_profile_82286d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubjectMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('resource_count', models.PositiveIntegerField(default=0)),
                ('current_focus', models.JSONField(blank=True, default=list)),
                ('weak_areas', models.JSONField(blank=True, default=list)),
                ('last_touched_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_memories', to='organizer.profile')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('profile', 'code')},
            },
        ),
    ]
