# Generated by Django 6.0.6 on 2026-07-19 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_exportbundle_integrationconnection_learningactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='setup_path',
            field=models.CharField(choices=[('manual', 'Manual setup'), ('makerere', 'Makerere support')], default='manual', max_length=16),
        ),
        migrations.CreateModel(
            name='AssignmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(blank=True, max_length=32)),
                ('title', models.CharField(max_length=180)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('submitted', 'Submitted'), ('missed', 'Missed'), ('archived', 'Archived')], default='open', max_length=16)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('muele', 'MUELE'), ('calendar', 'Calendar')], default='manual', max_length=16)),
                ('source_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_items', to='organizer.profile')),
            ],
            options={
                'ordering': ['status', 'due_at', '-created_at'],
                'indexes': [models.Index(fields=['profile', 'status', 'due_at'], name='organizer_a_profile_c85e05_idx'), models.Index(fields=['profile', 'subject_code'], name='organizer_a_profile_56435d_idx')],
            },
        ),
        migrations.CreateModel(
            name='FolderImportPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_path', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scanned', 'Scanned'), ('approved', 'Approved'), ('imported', 'Imported'), ('rejected', 'Rejected')], default='draft', max_length=16)),
                ('discovered_folders', models.JSONField(blank=True, default=list)),
                ('discovered_files', models.JSONField(blank=True, default=list)),
                ('proposed_subjects', models.JSONField(blank=True, default=list)),
                ('proposed_rules', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folder_import_plans', to='organizer.profile')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['profile', 'status'], name='organizer_f_profile_624aea_idx')],
            },
        ),
        migrations.CreateModel(
            name='FolderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('match_field', models.CharField(choices=[('filename', 'Filename'), ('extension', 'File extension'), ('mime', 'File type'), ('source_path', 'Source path')], default='filename', max_length=24)),
                ('operator', models.CharField(choices=[('contains', 'Contains'), ('equals', 'Equals'), ('starts_with', 'Starts with'), ('ends_with', 'Ends with'), ('regex', 'Regular expression')], default='contains', max_length=24)),
                ('pattern', models.CharField(max_length=240)),
                ('file_extensions', models.JSONField(blank=True, default=list)),
                ('subject_code', models.CharField(blank=True, max_length=32)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('destination_template', models.CharField(blank=True, max_length=512)),
                ('action', models.CharField(choices=[('route', 'Route file'), ('review', 'Send to inbox'), ('ignore', 'Ignore')], default='route', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_rules', to='organizer.profile')),
            ],
            options={
                'ordering': ['priority', 'name'],
                'indexes': [models.Index(fields=['profile', 'enabled', 'priority'], name='organizer_f_profile_218b59_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('subject_code', models.CharField(blank=True, max_length=32)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('done', 'Done')], default='active', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_goals', to='organizer.profile')),
            ],
            options={
                'ordering': ['status', 'target_date', '-created_at'],
                'indexes': [models.Index(fields=['profile', 'status'], name='organizer_s_profile_61f2ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubjectTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(choices=[('filename', 'Filename'), ('summary', 'Summary'), ('manual', 'Manual'), ('muele', 'MUELE')], default='filename', max_length=16)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_themes', to='organizer.profile')),
                ('subject_memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='organizer.subjectmemory')),
            ],
            options={
                'ordering': ['subject_code', '-weight', 'name'],
                'indexes': [models.Index(fields=['profile', 'subject_code'], name='organizer_s_profile_5103c7_idx')],
                'unique_together': {('profile', 'subject_code', 'name')},
            },
        ),
    ]
