# Generated by Django 6.0.6 on 2026-07-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_profile_setup_path_assignmentitem_folderimportplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedCourseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=255)),
                ('primary_value', models.CharField(max_length=64)),
                ('secondary_value', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=32)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False, help_text='Checked against an official Makerere source. Does not affect what other students see.')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('program', 'primary_value', 'secondary_value', 'code')},
            },
        ),
    ]
