# Generated by Django 6.0.6 on 2026-07-19 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_suggestedcourseunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MueleCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(help_text='MUELE/Moodle internal course ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(blank=True, help_text='e.g. CSC2100, BSE202', max_length=64)),
                ('auto_download', models.BooleanField(default=True, help_text='Automatically download new files from this course')),
                ('enrolled', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muele_courses', to='organizer.integrationconnection')),
            ],
            options={
                'ordering': ['course_name'],
                'indexes': [models.Index(fields=['connection', 'auto_download'], name='organizer_m_connect_77fe86_idx')],
                'unique_together': {('connection', 'course_id')},
            },
        ),
    ]
