# Generated by Django 6.0.6 on 2026-07-20 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0007_learningroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveevent',
            name='method',
            field=models.CharField(choices=[('course_code', 'Subject code in filename'), ('topic', 'Topic keyword match'), ('ai', 'AI classification'), ('ebook', 'Ebook detected'), ('sensitive', 'Sensitive filename/extension'), ('media', 'Media file type'), ('installer', 'Installer'), ('archive', 'Archive file'), ('work_unsorted', 'Code/project file'), ('unsorted', 'No match (Unsorted)'), ('needs_sorting', 'No match (Needs sorting)')], max_length=32),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('critical', 'Critical')], default='normal', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='organizer.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
