# Generated by Django 6.0.6 on 2026-07-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0008_alter_moveevent_method_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentitem',
            name='deadline_notified_stage',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
