# Generated by Django 6.0.6 on 2026-07-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0010_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
