# Generated by Django 6.0.6 on 2026-07-21 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0011_supportmessage_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconnection',
            name='provider',
            field=models.CharField(choices=[('muele', 'Makerere MUELE'), ('mak_timetable', 'Makerere Timetable'), ('moodle', 'Moodle'), ('calendar', 'Calendar'), ('drive', 'Cloud drive'), ('notion', 'Notion'), ('local', 'Local folder')], max_length=24),
        ),
        migrations.AlterField(
            model_name='moveevent',
            name='method',
            field=models.CharField(choices=[('course_code', 'Subject code in filename'), ('topic', 'Topic keyword match'), ('ai', 'Smart Orch suggestion'), ('ebook', 'Ebook detected'), ('sensitive', 'Sensitive filename/extension'), ('media', 'Media file type'), ('installer', 'Installer'), ('archive', 'Archive file'), ('work_unsorted', 'Code/project file'), ('unsorted', 'No subject or topic match'), ('needs_sorting', 'No active profile')], max_length=32),
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('teaching', 'Teaching'), ('recess', 'Recess Term'), ('test', 'Test'), ('examination', 'Examination')], max_length=16)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday')], null=True)),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('date_label', models.CharField(blank=True, max_length=120)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('course_code', models.CharField(blank=True, max_length=32)),
                ('course_name', models.CharField(blank=True, max_length=180)),
                ('room', models.CharField(blank=True, max_length=64)),
                ('lecturer', models.CharField(blank=True, max_length=120)),
                ('raw_group', models.CharField(max_length=64)),
                ('last_notified_on', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='organizer.integrationconnection')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='organizer.profile')),
            ],
            options={
                'ordering': ['kind', 'weekday', 'specific_date', 'start_time'],
                'indexes': [models.Index(fields=['profile', 'kind', 'weekday'], name='organizer_t_profile_9191dd_idx'), models.Index(fields=['profile', 'kind', 'specific_date'], name='organizer_t_profile_47f920_idx')],
            },
        ),
    ]
