# Generated by Codex on 2026-07-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizer", "0012_alter_integrationconnection_provider_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyFocusSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject_code", models.CharField(blank=True, max_length=32)),
                ("title", models.CharField(max_length=180)),
                ("target_minutes", models.PositiveIntegerField(default=25)),
                ("review_item_ids", models.JSONField(blank=True, default=list)),
                ("resource_ids", models.JSONField(blank=True, default=list)),
                ("weak_areas", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("active", "Active"), ("completed", "Completed"), ("abandoned", "Abandoned")], default="active", max_length=16)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="focus_sessions", to="organizer.profile")),
            ],
            options={
                "ordering": ["status", "-started_at"],
                "indexes": [
                    models.Index(fields=["profile", "status", "-started_at"], name="organizer_s_profile_8b561d_idx"),
                    models.Index(fields=["profile", "subject_code"], name="organizer_s_profile_5628d9_idx"),
                ],
            },
        ),
    ]
