# Generated by Django 6.0.6 on 2026-07-24 17:51

import django.db.models.deletion
from django.db import migrations, models


def migrate_inbox_items(apps, schema_editor):
    """Carries every existing SortingInboxItem row over into the new,
    broader SortDecision model before the old table is dropped later in
    this same migration. Old status values that no longer exist
    ("rerouted"/"ignored") map onto the closest new one
    ("approved"/"rejected") -- a rerouted item was still a successful move,
    just to a different folder than first suggested.

    GlobalSortCategory rows are deliberately NOT seeded here -- like
    AppSettings, they're seeded lazily via ensure_defaults() the first time
    they're needed (organizer.views.settings_edit), using
    organizer.core.paths' real, machine-specific defaults computed at that
    time. Seeding them here with placeholder paths would permanently block
    ensure_defaults()'s get_or_create from ever filling in the real ones."""
    SortingInboxItem = apps.get_model('organizer', 'SortingInboxItem')
    SortDecision = apps.get_model('organizer', 'SortDecision')

    status_map = {"pending": "pending", "approved": "approved", "rerouted": "approved", "ignored": "rejected"}
    # auto_now_add would otherwise silently overwrite created_at with "now"
    # for every migrated row -- disabled for the duration of this loop so
    # historical timestamps survive the move.
    created_at_field = SortDecision._meta.get_field('created_at')
    created_at_field.auto_now_add = False
    try:
        for item in SortingInboxItem.objects.all():
            was_moved = item.status in ("approved", "rerouted")
            SortDecision.objects.create(
                profile=item.profile,
                move_event=item.move_event,
                filename=item.filename,
                source_path=item.source_path,
                suggested_destination=item.suggested_destination,
                final_destination=item.suggested_destination if was_moved else "",
                decision_type="manual",
                confidence=int(item.confidence or 0),
                explanation=(item.reason or "")[:500],
                status=status_map.get(item.status, "pending"),
                matched_rule=(item.suggested_subject or "")[:120],
                created_at=item.created_at,
                resolved_at=item.resolved_at,
            )
    finally:
        created_at_field.auto_now_add = True


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0013_studyfocussession'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSortCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('media', 'Media (images, music, video)'), ('ebooks', 'Ebooks'), ('archives', 'Archives'), ('installers', 'Installers'), ('code', 'Code/project files'), ('sensitive', 'Sensitive files')], max_length=16, unique=True)),
                ('label', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=False)),
                ('destination_path', models.CharField(blank=True, max_length=1024)),
                ('mode', models.CharField(choices=[('review', 'Suggest -- always ask first'), ('auto_high_confidence', 'Auto-move when confident'), ('auto', 'Always auto-move')], default='review', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMemoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('match_type', models.CharField(choices=[('extension', 'File extension'), ('filename_contains', 'Filename contains'), ('folder_source', 'Source folder'), ('subject_code', 'Subject code'), ('mime_group', 'File type group')], default='extension', max_length=24)),
                ('match_value', models.CharField(max_length=240)),
                ('destination_path', models.CharField(max_length=1024)),
                ('confidence_boost', models.SmallIntegerField(default=25)),
                ('times_approved', models.PositiveIntegerField(default=0)),
                ('times_rejected', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-times_approved', 'match_type', 'match_value'],
            },
        ),
        migrations.CreateModel(
            name='SortDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=512)),
                ('source_path', models.CharField(blank=True, max_length=1024)),
                ('suggested_destination', models.CharField(blank=True, max_length=1024)),
                ('final_destination', models.CharField(blank=True, max_length=1024)),
                ('decision_type', models.CharField(choices=[('profile_auto', 'Profile auto-sort'), ('global_suggested', 'Global category suggestion'), ('global_auto', 'Global category auto-move'), ('held_sensitive', 'Held for review -- sensitive'), ('manual', 'Manual')], default='manual', max_length=24)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('explanation', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('moved', 'Moved'), ('undone', 'Undone')], default='pending', max_length=16)),
                ('matched_rule', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='sortinginboxitem',
            name='organizer_s_profile_82286d_idx',
        ),
        migrations.RenameIndex(
            model_name='studyfocussession',
            new_name='organizer_s_profile_54dd81_idx',
            old_name='organizer_s_profile_8b561d_idx',
        ),
        migrations.RenameIndex(
            model_name='studyfocussession',
            new_name='organizer_s_profile_1b33c2_idx',
            old_name='organizer_s_profile_5628d9_idx',
        ),
        migrations.AddField(
            model_name='appsettings',
            name='global_default_mode',
            field=models.CharField(choices=[('leave', 'Leave files alone'), ('suggest', 'Suggest only'), ('auto_confident', 'Auto only when confident')], default='leave', help_text='What to do with a file that matches no profile, rule, or enabled category.', max_length=16),
        ),
        migrations.AddField(
            model_name='moveevent',
            name='confidence',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0-100 confidence score at the time of the decision. Blank for older/manual rows.', null=True),
        ),
        migrations.AddField(
            model_name='moveevent',
            name='decision_source',
            field=models.CharField(blank=True, help_text='Matches SortDecision.decision_type -- which pipeline stage decided this.', max_length=24),
        ),
        migrations.AddField(
            model_name='moveevent',
            name='explanation',
            field=models.CharField(blank=True, help_text='Plain-language reason this file was moved here.', max_length=500),
        ),
        migrations.AddField(
            model_name='moveevent',
            name='undo_available',
            field=models.BooleanField(default=True, help_text='Set False once this move has been undone via organizer.core.undo.restore_move.'),
        ),
        migrations.AddField(
            model_name='organizationmemoryrule',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_memory_rules', to='organizer.profile'),
        ),
        migrations.AddField(
            model_name='sortdecision',
            name='move_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sort_decision', to='organizer.moveevent'),
        ),
        migrations.AddField(
            model_name='sortdecision',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sort_decisions', to='organizer.profile'),
        ),
        migrations.RunPython(migrate_inbox_items, _noop),
        migrations.RemoveField(
            model_name='sortinginboxitem',
            name='move_event',
        ),
        migrations.RemoveField(
            model_name='sortinginboxitem',
            name='profile',
        ),
        migrations.AddIndex(
            model_name='organizationmemoryrule',
            index=models.Index(fields=['profile', 'enabled', 'match_type'], name='organizer_o_profile_f02f13_idx'),
        ),
        migrations.AddIndex(
            model_name='sortdecision',
            index=models.Index(fields=['profile', 'status'], name='organizer_s_profile_1438b3_idx'),
        ),
        migrations.DeleteModel(
            name='SortingInboxItem',
        ),
    ]
