# Generated by Django 6.0.6 on 2026-07-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0014_trust_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentitem',
            name='checklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='assignmentitem',
            name='evidence_path',
            field=models.CharField(blank=True, help_text="A file or folder the student points at as proof of work -- a draft, a submission screenshot, whatever counts as evidence this isn't being ignored.", max_length=1024),
        ),
    ]
