# Generated by Django 6.0.6 on 2026-07-24 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0015_assignment_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastPaperAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=32)),
                ('paper_count', models.PositiveIntegerField(default=0)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('marks_by_topic', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_paper_analyses', to='organizer.profile')),
            ],
            options={
                'ordering': ['subject_code'],
                'unique_together': {('profile', 'subject_code')},
            },
        ),
    ]
