# Generated by Django 6.0.6 on 2026-07-24 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0016_past_paper_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=32)),
                ('coursework_weight', models.PositiveSmallIntegerField(default=30, help_text='Percent of the final grade')),
                ('coursework_score', models.PositiveSmallIntegerField(blank=True, help_text='Blank means not yet scored', null=True)),
                ('test_weight', models.PositiveSmallIntegerField(default=0, help_text='Percent of the final grade')),
                ('test_score', models.PositiveSmallIntegerField(blank=True, help_text='Blank means not yet scored', null=True)),
                ('exam_weight', models.PositiveSmallIntegerField(default=70, help_text='Percent of the final grade')),
                ('target_percent', models.PositiveSmallIntegerField(default=70, help_text='Overall percentage target')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_targets', to='organizer.profile')),
            ],
            options={
                'ordering': ['subject_code'],
                'unique_together': {('profile', 'subject_code')},
            },
        ),
    ]
