# Generated by Django 6.0.6 on 2026-07-24 19:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0017_grade_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(blank=True, max_length=32)),
                ('card_type', models.CharField(choices=[('past_paper_question', 'Past paper question'), ('definition', 'Definition'), ('concept', 'Concept explainer'), ('manual', 'Manual')], default='manual', max_length=24)),
                ('front', models.CharField(max_length=500)),
                ('back', models.TextField(blank=True, help_text='Blank is valid -- e.g. a past-paper question with no known answer.')),
                ('source_label', models.CharField(blank=True, help_text='The file this card was generated from, if any', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('interval_index', models.PositiveSmallIntegerField(default=0)),
                ('due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('times_seen', models.PositiveIntegerField(default=0)),
                ('times_correct', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='organizer.profile')),
            ],
            options={
                'ordering': ['due_at'],
                'indexes': [models.Index(fields=['profile', 'status', 'due_at'], name='organizer_f_profile_08a821_idx'), models.Index(fields=['profile', 'subject_code'], name='organizer_f_profile_c563a9_idx')],
            },
        ),
    ]
