# Generated by Django 6.0.6 on 2026-07-24 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0018_flashcards'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_digests', to='organizer.profile')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='CareerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_track', models.CharField(blank=True, choices=[('backend_engineer', 'Backend Engineer'), ('ai_engineer', 'AI Engineer'), ('cybersecurity_analyst', 'Cybersecurity Analyst'), ('data_analyst', 'Data Analyst'), ('mobile_developer', 'Mobile Developer'), ('cloud_engineer', 'Cloud Engineer'), ('other', 'Other')], max_length=32)),
                ('weekly_goal', models.CharField(blank=True, max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_profile', to='organizer.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('problem_statement', models.TextField(blank=True)),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('idea', 'Idea'), ('building', 'Building'), ('testing', 'Testing'), ('shipped', 'Shipped')], default='idea', max_length=16)),
                ('github_url', models.URLField(blank=True)),
                ('folder_path', models.CharField(blank=True, max_length=1024)),
                ('lessons_learned', models.TextField(blank=True)),
                ('portfolio_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizer.profile')),
            ],
            options={
                'ordering': ['status', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('project_update', 'Project update'), ('lesson_learned', 'Lesson learned'), ('course_reflection', 'Course reflection'), ('society_event', 'Society/event participation'), ('tutorial', 'Tutorial thread'), ('problem_solution', 'Problem/solution story'), ('portfolio_launch', 'Portfolio launch'), ('internship_update', 'Internship search update')], default='project_update', max_length=24)),
                ('topic', models.CharField(blank=True, help_text='Free-text label for a draft not tied to a project or digest', max_length=200)),
                ('raw_text', models.TextField()),
                ('polished_text', models.TextField(blank=True)),
                ('professional_text', models.TextField(blank=True)),
                ('short_text', models.TextField(blank=True)),
                ('website_text', models.TextField(blank=True)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('posted', 'Posted')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career_digest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_drafts', to='organizer.careerdigest')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_drafts', to='organizer.profile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_drafts', to='organizer.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='organizer.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='careerdigest',
            index=models.Index(fields=['profile', '-period_end'], name='organizer_c_profile_094adf_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['profile', 'status'], name='organizer_p_profile_e44185_idx'),
        ),
        migrations.AddIndex(
            model_name='contentdraft',
            index=models.Index(fields=['profile', 'status'], name='organizer_c_profile_d90786_idx'),
        ),
    ]
