# Generated by Django 6.0.6 on 2026-07-24 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0019_career_tab'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='careerdigest',
            unique_together={('profile', 'period_start')},
        ),
    ]
