# Generated by Django 6.0.6 on 2026-07-25 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0020_career_digest_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconnection',
            name='provider',
            field=models.CharField(choices=[('muele', 'Makerere MUELE'), ('mak_timetable', 'Makerere Timetable'), ('moodle', 'Moodle'), ('calendar', 'Calendar'), ('drive', 'Cloud drive'), ('notion', 'Notion'), ('local', 'Local folder'), ('custom_website', 'Custom website API'), ('markdown_export', 'Markdown export'), ('html_export', 'HTML export'), ('manual_copy', 'Manual copy'), ('linkedin', 'LinkedIn')], max_length=24),
        ),
        migrations.CreateModel(
            name='PublishedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(choices=[('raw', 'Raw'), ('polished', 'Polished'), ('professional', 'Professional'), ('short', 'Short'), ('website', 'Website')], default='raw', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('payload_sent', models.JSONField(blank=True, default=dict)),
                ('response_status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('external_url', models.URLField(blank=True)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_posts', to='organizer.integrationconnection')),
                ('content_draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_posts', to='organizer.contentdraft')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_draft', '-created_at'], name='organizer_p_content_e6c3af_idx')],
            },
        ),
    ]
