# Generated by Django 6.0.6 on 2026-07-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0021_publishing_connectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_stars',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='integrationconnection',
            name='provider',
            field=models.CharField(choices=[('muele', 'Makerere MUELE'), ('mak_timetable', 'Makerere Timetable'), ('moodle', 'Moodle'), ('calendar', 'Calendar'), ('drive', 'Cloud drive'), ('notion', 'Notion'), ('local', 'Local folder'), ('custom_website', 'Custom website API'), ('markdown_export', 'Markdown export'), ('html_export', 'HTML export'), ('manual_copy', 'Manual copy'), ('linkedin', 'LinkedIn'), ('github', 'GitHub')], max_length=24),
        ),
        migrations.AlterField(
            model_name='resourcerecommendation',
            name='source_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('book', 'Book'), ('article', 'Article'), ('github_repo', 'GitHub repo')], max_length=16),
        ),
    ]
