# Generated by Django 6.0.6 on 2026-07-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0022_github_connector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconnection',
            name='status',
            field=models.CharField(choices=[('planned', 'Ready to connect'), ('connected', 'Connected'), ('needs_key', 'Needs a key or token'), ('paused', 'Paused'), ('error', 'Needs attention')], default='planned', max_length=24),
        ),
    ]
