# Generated by Django 6.0.6 on 2026-07-25 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0024_integration_configured_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='source',
            field=models.CharField(choices=[('synced', 'Synced'), ('manual', 'Manual')], default='synced', max_length=8),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='connection',
            field=models.ForeignKey(blank=True, help_text="Null for a manually-added entry -- there's no live source to attribute it to.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='organizer.integrationconnection'),
        ),
        migrations.CreateModel(
            name='TimetableDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('teaching', 'Teaching'), ('recess', 'Recess Term'), ('test', 'Test'), ('examination', 'Examination'), ('other', 'Other')], default='other', max_length=16)),
                ('title', models.CharField(max_length=180)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=1024)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_documents', to='organizer.profile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
