# Generated by Django 6.0.6 on 2026-07-25 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0025_timetableentry_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('sort_file', 'Sort file'), ('muele_sync', 'MUELE sync'), ('summary_generate', 'Summary generation'), ('course_guide_generate', 'Course guide generation'), ('page_load', 'Page load'), ('drive_backup', 'Drive backup'), ('github_publish', 'GitHub publish'), ('folder_import_scan', 'Folder import scan')], max_length=32)),
                ('duration_ms', models.PositiveIntegerField()),
                ('query_count', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='organizer.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['operation', '-created_at'], name='organizer_p_operati_6de26f_idx')],
            },
        ),
    ]
