# Generated by Django 6.0.6 on 2026-07-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0026_performancemetric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancemetric',
            name='operation',
            field=models.CharField(choices=[('sort_file', 'Sort file'), ('muele_sync', 'MUELE sync'), ('timetable_sync', 'Timetable sync'), ('summary_generate', 'Summary generation'), ('course_guide_generate', 'Course guide generation'), ('page_load', 'Page load'), ('drive_backup', 'Drive backup'), ('github_publish', 'GitHub publish'), ('folder_import_scan', 'Folder import scan')], max_length=32),
        ),
    ]
