# Generated by Django 6.0.6 on 2026-07-25 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0027_alter_performancemetric_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('muele_sync', 'MUELE sync'), ('timetable_sync', 'Timetable sync'), ('drive_backup', 'Drive backup'), ('summary_generate', 'Summary generation'), ('course_guide_generate', 'Course guide generation'), ('folder_import_scan', 'Folder import scan'), ('github_publish', 'GitHub publish'), ('large_folder_sort', 'Large folder sort')], max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('progress_current', models.PositiveIntegerField(default=0)),
                ('progress_total', models.PositiveIntegerField(blank=True, null=True)),
                ('result_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_tasks', to='organizer.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
