# Generated by Django 6.0.6 on 2026-07-25 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0029_search_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileIndexEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024)),
                ('size', models.BigIntegerField()),
                ('modified_at', models.FloatField(help_text='Raw stat().st_mtime at last scan.')),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('last_classification', models.CharField(blank=True, max_length=255)),
                ('last_summary_status', models.CharField(blank=True, max_length=32)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_index_entries', to='organizer.profile')),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'path'), name='unique_file_index_entry_per_profile_path')],
            },
        ),
    ]
