# Generated by Django 6.0.6 on 2026-07-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0030_fileindexentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundtask',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('cancelling', 'Cancelling'), ('cancelled', 'Cancelled')], default='queued', max_length=16),
        ),
    ]
