# Generated by Django 6.0.6 on 2026-07-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0031_alter_backgroundtask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='moveevent',
            name='drive_backup_status',
            field=models.CharField(choices=[('not_attempted', 'Not attempted'), ('success', 'Backed up'), ('failed', 'Failed')], default='not_attempted', help_text="Set by organizer.core.drive_api.backup_file's fire-and-forget upload after a move. 'failed' covers offline/quota/not-connected as well as a real upload error -- anything that means the file isn't actually backed up yet.", max_length=16),
        ),
    ]
