# Generated by Django 6.0.6 on 2026-07-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0033_fileindexentry_profile_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dismissed_setup_items',
            field=models.JSONField(blank=True, default=list, help_text="Keys of optional setup checklist items the user chose to hide (see dashboard's service mesh)."),
        ),
    ]
