# Generated by Django 6.0.6 on 2026-07-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0034_profile_dismissed_setup_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='app_state',
            field=models.JSONField(blank=True, default=dict, help_text="Optional diagnostic snapshot (app version, setup status, recent errors) the sender chose to attach from the support popup's 'Include app diagnostics' checkbox."),
        ),
    ]
