# Generated by Django 6.0.7 on 2026-07-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0035_supportmessage_app_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsortcategory',
            name='mode',
            field=models.CharField(choices=[('review', 'Suggest (always ask first)'), ('auto_high_confidence', 'Auto-move when confident'), ('auto', 'Always auto-move')], default='review', max_length=24),
        ),
        migrations.AlterField(
            model_name='sortdecision',
            name='decision_type',
            field=models.CharField(choices=[('profile_auto', 'Profile auto-sort'), ('global_suggested', 'Global category suggestion'), ('global_auto', 'Global category auto-move'), ('held_sensitive', 'Held for review (sensitive)'), ('manual', 'Manual')], default='manual', max_length=24),
        ),
    ]
