"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import json
import os
from pathlib import Path

from runtime import app_dir

# Project root in development; the folder containing the exe once frozen by
# PyInstaller, so db.sqlite3 persists across runs instead of living inside a
# temporary bundle extraction directory that gets wiped every launch.
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = app_dir()


# ---------------------------------------------------------------------------
# Secret config (gitignored) -- django_secret_key, debug, etc.
# Auto-created on first run if missing (e.g. a freshly downloaded exe has
# never had this file), so a real per-install secret key exists and DEBUG
# defaults to off -- a downloaded app should never show a stranger's local
# file paths and full tracebacks in a raw Django debug page. Set
# "debug": true in secret_config.json by hand for local development.
# ---------------------------------------------------------------------------
_SECRET_CONFIG_PATH = BASE_DIR / "secret_config.json"

def _load_or_create_secret_config():
    try:
        with open(_SECRET_CONFIG_PATH, encoding="utf-8") as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        pass

    import secrets

    config = {
        "django_secret_key": secrets.token_urlsafe(64),
        "debug": False,
    }
    try:
        with open(_SECRET_CONFIG_PATH, "w", encoding="utf-8") as f:
            json.dump(config, f, indent=2)
    except OSError:
        pass  # Install location isn't writable; use this key for the current run only.
    return config

_secret_config = _load_or_create_secret_config()

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _secret_config.get(
    "django_secret_key",
    os.environ.get("DJANGO_SECRET_KEY", "django-insecure-++m(k_o&f$6!b^#axe(4r(fb66=cjbw_5a7kwvyyn1w=&s2jmo"),
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _secret_config.get("debug", os.environ.get("DJANGO_DEBUG", "False").lower() in ("true", "1", "yes"))

# Orch's server only ever binds to 127.0.0.1 (see gui/server.py) -- it never
# needs to answer to any other Host header.
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# Without this, Django's own default logging config sends request-handling
# errors (an unhandled exception in any view) to a mail_admins handler that
# does nothing without configured ADMINS/an email backend, plus a console
# handler that's only active when DEBUG=True. DEBUG=False is the shipped
# default (see secret_config.json above) -- meaning, without this, a real
# exception in the field leaves literally no trace anywhere: no log file, no
# console output, nothing to diagnose from a bug report beyond "it broke."
# A rotating file handler here means there's always somewhere to look.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(BASE_DIR / "orch-error.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 3,
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["file"],
        "level": "ERROR",
    },
    "loggers": {
        "django": {
            "handlers": ["file"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'organizer',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'organizer.context_processors.owner_console',
                'organizer.context_processors.desktop_shell',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            # Orch has no single "the server" thread touching this database:
            # the watcher, background jobs, the dashboard's own requests,
            # and the performance-metric writer all hit it from separate
            # threads, often within the same moment (e.g. a sort landing
            # while the dashboard is mid-render). SQLite's own default
            # journal mode lets writers block readers and vice versa, and
            # Python's sqlite3 default busy timeout is only 5s -- both of
            # those are exactly what several call sites elsewhere were
            # already defensively catching as "db down" instead of fixing
            # at the root. WAL lets readers and one writer proceed without
            # blocking each other; a longer timeout gives real contention
            # more room before it actually surfaces as an error.
            'timeout': 20,
            'init_command': 'PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;',
        },
    }
}


# In-process cache for a few explicitly signal-invalidated computations
# (see organizer/core/resource_cache.py) -- local memory, not a paid
# service, and deliberately NOT persisted across restarts: this process is
# the only thing that ever writes the cached data (gui/server.py runs the
# whole app, GUI included, in one process), so a stale value can only ever
# come from *this* run, and losing the cache on restart is a feature, not
# a bug, here.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Orch is a single-user desktop app -- every timestamp it shows should be
# this machine's actual local time, not a fixed zone that assumes where in
# the world the user is. tzlocal reads the OS's own timezone configuration
# (handles the Windows-name-to-IANA mapping too) rather than us guessing.
try:
    from tzlocal import get_localzone_name
    TIME_ZONE = get_localzone_name()
except Exception:
    TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# ---------------------------------------------------------------------------
# Support email (gitignored) -- SMTP settings for the "Contact support"
# popup, same config-file pattern as ai_config.json. Off (console backend,
# just logs instead of sending) until support_email.json exists, so a fresh
# install never silently fails trying to reach a real mail server.
# ---------------------------------------------------------------------------
_SUPPORT_EMAIL_CONFIG_PATH = BASE_DIR / "support_email.json"

def _load_support_email_config():
    try:
        with open(_SUPPORT_EMAIL_CONFIG_PATH, encoding="utf-8") as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return {}

_support_email_config = _load_support_email_config()

SUPPORT_EMAIL_CONFIGURED = bool(_support_email_config.get("smtp_host"))
SUPPORT_INBOX_ADDRESS = "iranziresponse@gmail.com"

if SUPPORT_EMAIL_CONFIGURED:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = _support_email_config.get("smtp_host", "")
    EMAIL_PORT = int(_support_email_config.get("smtp_port", 587))
    EMAIL_HOST_USER = _support_email_config.get("smtp_user", "")
    EMAIL_HOST_PASSWORD = _support_email_config.get("smtp_password", "")
    EMAIL_USE_TLS = bool(_support_email_config.get("use_tls", True))
    DEFAULT_FROM_EMAIL = _support_email_config.get("from_address") or EMAIL_HOST_USER
else:
    # No config yet: never try to actually reach a mail server. Messages
    # are still saved to the database (see organizer.models.SupportMessage)
    # so nothing is lost while support_email.json isn't set up.
    EMAIL_BACKEND = "django.core.mail.backends.locmem.EmailBackend"
